const DIVERSITY_CONFIG = {
  WEIGHTS: {
    EXACT_MATCH: 0.3,
    CATEGORY_REPETITION: 0.15,
    RECENCY_REPEAT: 0.08,
    MULTI_DAY_REPEAT: 0.04,
    ROTATION_MISMATCH: 0.03,
  },
  DEFAULT_CATEGORY_THRESHOLD: 3,
  DEFAULT_RECENCY_WINDOW: 3,
};

module.exports = {
  DIVERSITY_CONFIG,
};
