import { z } from "zod";
import { apiClient } from "@/services/api/apiClient";
import type { AIRequest, AIResponse } from "./ai.contract";
import { AIRequestType } from "./ai.contract";

const INVALID_REQUEST_MESSAGE = "Meal plans are generated by the system. Ask for explanation instead.";
const EXPLAIN_NOT_AVAILABLE_MESSAGE = "Explanation not available";

const orchestrateRequestSchema = z.object({
  user_input: z.string().min(1),
  session_id: z.string().min(1).optional(),
  context: z.record(z.unknown()).optional(),
}).strict();

const orchestrateResponseSchema = z.object({
  intent: z.enum(["EXPLAIN_DECISION", "KNOWLEDGE_QUERY", "INTERPRET_SYMPTOMS", "INVALID_REQUEST"]),
  routed_endpoint: z.string().nullable().optional(),
  text: z.string().optional(),
  message: z.string().optional(),
  session_id: z.string().optional(),
  meta: z.object({
    fallback: z.boolean().optional(),
    reason: z.string().optional(),
    mode: z.string().optional(),
  }).optional(),
}).strict();

const explainRequestSchema = z.object({
  query: z.string().min(1),
  session_id: z.string().min(1),
  decision_trace: z.record(z.unknown()),
  selected_meal: z.record(z.unknown()),
  constraints_applied: z.record(z.unknown()),
  context: z.record(z.unknown()).optional(),
}).strict();

const explainResponseSchema = z.object({
  text: z.string(),
  session_id: z.string().optional(),
  meta: z.object({
    fallback: z.boolean().optional(),
    reason: z.string().optional(),
    mode: z.string().optional(),
  }).optional(),
}).strict();

type OrchestrateResponse = z.infer<typeof orchestrateResponseSchema>;
type ExplainResponse = z.infer<typeof explainResponseSchema>;

function toMeta(meta: unknown) {
  if (!meta || typeof meta !== "object") {
    return { fallback: false, reason: "ok", mode: "normal" };
  }

  const safeMeta = meta as Record<string, unknown>;
  return {
    fallback: Boolean(safeMeta.fallback),
    reason: typeof safeMeta.reason === "string" ? safeMeta.reason : "ok",
    mode: typeof safeMeta.mode === "string" ? safeMeta.mode : (Boolean(safeMeta.fallback) ? "fallback" : "normal"),
  };
}

function isNonEmptyObject(value: unknown): value is Record<string, unknown> {
  return Boolean(value && typeof value === "object" && !Array.isArray(value) && Object.keys(value as Record<string, unknown>).length > 0);
}

function asRecord(value: unknown): Record<string, unknown> {
  return value && typeof value === "object" && !Array.isArray(value) ? (value as Record<string, unknown>) : {};
}

async function callOrchestrator(request: AIRequest): Promise<AIResponse> {
  const query = typeof request.query === "string" ? request.query.trim() : "";
  if (!query) {
    return { success: false, error: "INSUFFICIENT_CONTEXT" };
  }

  const context = request.context || {};
  const sessionId = typeof context.session_id === "string" ? context.session_id : undefined;

  const response = await apiClient<OrchestrateResponse>({
    method: "POST",
    path: "/assistant/orchestrate",
    body: {
      user_input: query,
      ...(sessionId ? { session_id: sessionId } : {}),
      context,
    },
    requestSchema: orchestrateRequestSchema,
    responseSchema: orchestrateResponseSchema,
  });

  if (response.error || !response.data) {
    return { success: false, error: "INSUFFICIENT_CONTEXT" };
  }

  const text = response.data.text || response.data.message;
  if (!text || !text.trim()) {
    return { success: false, error: "INSUFFICIENT_CONTEXT" };
  }

  return {
    success: true,
    data: { text: text.trim() },
    meta: toMeta(response.data.meta),
    error: null,
  };
}

async function callExplainAPI(request: AIRequest): Promise<AIResponse> {
  const query = typeof request.query === "string" ? request.query.trim() : "";
  const context = asRecord(request.context);
  const currentPlan = asRecord(context.current_plan);
  const sessionId = typeof context.session_id === "string" ? context.session_id : "";
  const explainRequested = context.explain_requested === true;

  const decisionTrace = isNonEmptyObject(context.decision_trace)
    ? context.decision_trace
    : (isNonEmptyObject(context.trace)
      ? context.trace
      : (isNonEmptyObject(currentPlan.decision_trace)
        ? currentPlan.decision_trace
        : (isNonEmptyObject(currentPlan.trace) ? currentPlan.trace : null)));

  const selectedMeal = isNonEmptyObject(context.selected_meal)
    ? context.selected_meal
    : (isNonEmptyObject(currentPlan.selected_meal) ? currentPlan.selected_meal : null);

  const constraintsApplied = isNonEmptyObject(context.constraints_applied)
    ? context.constraints_applied
    : (isNonEmptyObject(currentPlan.constraints_applied) ? currentPlan.constraints_applied : null);

  if (!explainRequested || !query || !sessionId || !decisionTrace || !selectedMeal || !constraintsApplied) {
    return {
      success: true,
      data: { text: EXPLAIN_NOT_AVAILABLE_MESSAGE },
      meta: { fallback: true, reason: "deterministic_only", mode: "fallback" },
      error: "INSUFFICIENT_CONTEXT",
    };
  }

  const response = await apiClient<ExplainResponse>({
    method: "POST",
    path: "/ai/explain",
    body: {
      query,
      session_id: sessionId,
      decision_trace: decisionTrace,
      selected_meal: selectedMeal,
      constraints_applied: constraintsApplied,
      context,
    },
    requestSchema: explainRequestSchema,
    responseSchema: explainResponseSchema,
  });

  if (response.error || !response.data) {
    return {
      success: true,
      data: { text: EXPLAIN_NOT_AVAILABLE_MESSAGE },
      meta: { fallback: true, reason: "deterministic_only", mode: "fallback" },
      error: null,
    };
  }

  const meta = toMeta(response.data.meta);
  if (meta.reason === "deterministic_only") {
    return {
      success: true,
      data: { text: EXPLAIN_NOT_AVAILABLE_MESSAGE },
      meta,
      error: null,
    };
  }

  return {
    success: true,
    data: { text: response.data.text.trim() },
    meta,
    error: null,
  };
}

export async function routeAI(request: AIRequest): Promise<AIResponse> {
  switch (request.type) {
    case AIRequestType.EXPLAIN_DECISION:
      return callExplainAPI(request);
    case AIRequestType.KNOWLEDGE_QUERY:
    case AIRequestType.INTERPRET_SYMPTOMS:
      return callOrchestrator(request);
    case AIRequestType.INVALID_REQUEST:
      return {
        success: true,
        data: { text: INVALID_REQUEST_MESSAGE },
        meta: { fallback: false, reason: "invalid_request", mode: "normal" },
        error: null,
      };
    default:
      return {
        success: false,
        error: "Unsupported AI request type.",
      };
  }
}
