import { useEffect, useRef, useState } from "react";
import { queryKnowledgeApi } from "@/services/api/knowledge.api";
import { classifyIntent } from "@/ai/intentClassifier";
import { AIRequestType } from "@/ai/ai.contract";
import { EngineeringPageHeader } from "@/components/ui/EngineeringPageHeader";
import { StatusPill } from "@/components/ui/StatusPill";

type Message = {
  id: string;
  role: "user" | "assistant";
  content: string;
  sources?: string[];
  isFallback?: boolean;
  fallbackReason?: string;
};

export default function KnowledgePage() {
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const [messages, setMessages] = useState<Message[]>([
    {
      id: "knowledge_welcome",
      role: "assistant",
      content:
        "Assistive Q&A only: Ayurvedic knowledge from retrieval. This path cannot generate or change meal plans — use Planner for decisions.",
    },
  ]);
  const scrollerRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    if (!scrollerRef.current) return;
    scrollerRef.current.scrollTop = scrollerRef.current.scrollHeight;
  }, [messages, loading]);

  const send = async () => {
    const query = input.trim();
    if (!query || loading) return;

    const intent = classifyIntent(query);
    if (intent === AIRequestType.INVALID_REQUEST) {
      setMessages((curr) => [
        ...curr,
        {
          id: `a_invalid_${Date.now()}`,
          role: "assistant",
          content: "Meal plans are generated by the deterministic engine. Ask for explanation or Ayurvedic context instead.",
          isFallback: true,
          fallbackReason: "invalid_request",
        },
      ]);
      setInput("");
      return;
    }

    setMessages((curr) => [...curr, { id: `u_${Date.now()}`, role: "user", content: query }]);
    setInput("");
    setLoading(true);

    try {
      const response = await queryKnowledgeApi(query);
      if (response.error || !response.data) {
        setMessages((curr) => [
          ...curr,
          {
            id: `a_err_${Date.now()}`,
            role: "assistant",
            content: "Could not reach the knowledge service. Try rephrasing or check backend health.",
            isFallback: true,
            fallbackReason: "api_error",
          },
        ]);
        return;
      }

      const data = response.data;
      const isFallback = Boolean(data.meta && data.meta.fallback);
      setMessages((curr) => [
        ...curr,
        {
          id: `a_${Date.now()}`,
          role: "assistant",
          content: data.answer,
          sources: data.sources,
          isFallback,
          fallbackReason: data.meta?.reason,
        },
      ]);
    } catch {
      setMessages((curr) => [
        ...curr,
        {
          id: `a_fail_${Date.now()}`,
          role: "assistant",
          content: "Request failed. No plan or ranking data is sent to this endpoint.",
          isFallback: true,
          fallbackReason: "request_failed",
        },
      ]);
    } finally {
      setLoading(false);
    }
  };

  return (
    <section className="space-y-5 ui-fade-in">
      <EngineeringPageHeader
        title="Assistive Q&A"
        description="Read-only Ayurvedic retrieval. Bounded assistive layer — not a meal planner or chatbot that overrides the engine."
        meta={
          <>
            <StatusPill label="No plan mutations" tone="ok" />
            <StatusPill label="RAG / knowledge" tone="info" />
          </>
        }
      />

      <article className="eng-panel flex flex-col p-4">
        <div
          ref={scrollerRef}
          className="ui-chat-scroll min-h-[420px] max-h-[58vh] flex-1 space-y-2 overflow-y-auto rounded-md border border-slate-200 bg-slate-50 p-3"
        >
          {messages.map((msg) => (
            <div
              key={msg.id}
              className={`max-w-[90%] rounded-lg px-3 py-2 text-sm ${
                msg.role === "user"
                  ? "ml-auto bg-indigo-600 text-white"
                  : "border border-slate-200 bg-white text-slate-800"
              }`}
            >
              <p className="whitespace-pre-wrap">{msg.content}</p>
              {msg.role === "assistant" && msg.isFallback ? (
                <p className="mt-1 font-mono text-[10px] text-amber-700">
                  fallback:{msg.fallbackReason || "unknown"}
                </p>
              ) : null}
              {msg.role === "assistant" && Array.isArray(msg.sources) && msg.sources.length > 0 ? (
                <p className="mt-1 text-[11px] text-slate-500">Sources: {msg.sources.join(" · ")}</p>
              ) : null}
            </div>
          ))}
          {loading ? <p className="text-xs text-slate-500">Retrieving…</p> : null}
        </div>

        <div className="mt-3 flex gap-2 border-t border-slate-100 pt-3">
          <input
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter") {
                e.preventDefault();
                void send();
              }
            }}
            placeholder="Ask about foods, seasons, or Ayurvedic concepts…"
            disabled={loading}
            className="flex-1 rounded-md border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900 placeholder:text-slate-400 focus:border-indigo-500 focus:outline-none focus:ring-1 focus:ring-indigo-500"
          />
          <button
            type="button"
            onClick={() => {
              void send();
            }}
            disabled={loading || input.trim().length === 0}
            className="eng-btn-primary shrink-0"
          >
            Send
          </button>
        </div>
      </article>
    </section>
  );
}
